language: shell
install: source install.sh
script: nix-shell -p cowsay --command "cowsay wooo?"
# Bare "nix" command hidden behind a flag in unstable
# script: nix run nixpkgs.cowsay -c cowsay wooo?

_cachix_push: &cachix_push
  after_success:
    - comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all| grep -v '\.drv$' | sort) | cachix push $CACHIX_CACHE

jobs:
  include:
    # test the default install across many OS/versions
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode12
