language: shell
install: source install.sh
script: nix run nixpkgs.cowsay -c cowsay wooo?

_cachix_push: &cachix_push
  after_success:
    - comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all| grep -v '\.drv$' | sort) | cachix push $CACHIX_CACHE

jobs:
  include:
    # test the default install across many OS/versions
    - name: shellcheck
      stage: lint
      os: linux
      script: shellcheck install.sh
      install: echo "Skipping install; Travis-CI includes shellcheck."
    - os: linux
      stage: os/version tests
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode12

    # test specific features (but less broadly/specifically)
    # going with Linux only because it's faster...
    - name: use cachix
      stage: feature tests
      os: linux
      env:
        - CACHIX_CACHE: nix-travis-ci
        - secure: WczEmmAfi5H43lI3XHhygQPIb6KK8EfWgIUoqsvGboLC3GpO0myNAKPCVKymaQGvm+NcXphBgbZoN0LWAN1X7vtjWwxX2lmF3gqQqHgVvA/g3x8vZQApr4dGJ2NvdSh8agp0xceREhytHVroXOq8i3YfKlnEl4QwhiWYcOMq+OENmo8FFlNVnI6jcrB8t0QDi/JiRW2b+nZsXQtU6y/XMw/a/tvHMvlyQkYEL0gi3VYkosJxmsDwCJmaYZ2twCP5ByxQbq0zyXQoON6Uqt5GAsLKmg6X2KP/MOFQcxcezdsIzjhJC6yaQLl19FrQGDNVCXNPHOrp9iHziwmJT7tJyB5AhiGraXLm8zkWQEZTK5FR8QeSJts5fWAlj9W2QuJejHGQ2SDVBLmtoXJqjyCFWGgoKtIQ9pFdgIB3QC+4WZOdaAvZiJHYzLqfvPkMDHHkBnA/WY2XvuDVJJ6FFZhdjBzxnx81WUZgZ1zJxQiF/lCzZqPvcwRrBzP36vSFiXeTUxDhjfKJEw1OPNDemRLlvrX78excGCVbr0W1JXwpEGFfUD8dJUV0SS4kQJDid0RELMVG/LkPw+LckjfEHqd8w7ib6KGaRq7eTCCLyfmaEPNNBB9bVvSCQsuvD80MhM7OcAazKSG0qhM2Uo5teGb7qNI2gdnpdczYise5tRgpuhA=
      <<: *cachix_push

    - name: skip adding nixpkgs channel
      os: linux
      env:
        - SKIP_ADDING_NIXPKGS_CHANNEL: true
      script:
        # fail w/o nixpkgs
        - nix run nixpkgs.cowsay -c cowsay wooo? && exit 1 || echo "Failed as expected"
        # succeed w/ nixpkgs
        - NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/tarball/ab5863afada3c1b50fc43bf774b75ea71b287cde nix run nixpkgs.cowsay -c cowsay Succeeded as expected

    - name: set nixpkgs channel via NIX_PATH
      os: linux
      env:
        - NIX_PATH: nixpkgs=channel:nixos-20.03

    - name: use cachix with explicit channel
      os: linux
      env:
        - CACHIX_CACHE: nix-travis-ci
        - secure: WczEmmAfi5H43lI3XHhygQPIb6KK8EfWgIUoqsvGboLC3GpO0myNAKPCVKymaQGvm+NcXphBgbZoN0LWAN1X7vtjWwxX2lmF3gqQqHgVvA/g3x8vZQApr4dGJ2NvdSh8agp0xceREhytHVroXOq8i3YfKlnEl4QwhiWYcOMq+OENmo8FFlNVnI6jcrB8t0QDi/JiRW2b+nZsXQtU6y/XMw/a/tvHMvlyQkYEL0gi3VYkosJxmsDwCJmaYZ2twCP5ByxQbq0zyXQoON6Uqt5GAsLKmg6X2KP/MOFQcxcezdsIzjhJC6yaQLl19FrQGDNVCXNPHOrp9iHziwmJT7tJyB5AhiGraXLm8zkWQEZTK5FR8QeSJts5fWAlj9W2QuJejHGQ2SDVBLmtoXJqjyCFWGgoKtIQ9pFdgIB3QC+4WZOdaAvZiJHYzLqfvPkMDHHkBnA/WY2XvuDVJJ6FFZhdjBzxnx81WUZgZ1zJxQiF/lCzZqPvcwRrBzP36vSFiXeTUxDhjfKJEw1OPNDemRLlvrX78excGCVbr0W1JXwpEGFfUD8dJUV0SS4kQJDid0RELMVG/LkPw+LckjfEHqd8w7ib6KGaRq7eTCCLyfmaEPNNBB9bVvSCQsuvD80MhM7OcAazKSG0qhM2Uo5teGb7qNI2gdnpdczYise5tRgpuhA=
        - NIX_PATH: nixpkgs=channel:nixos-20.03
      <<: *cachix_push

    - name: specify install url
      os: linux
      env:
        - NIX_URL: https://releases.nixos.org/nix/nix-2.3.1/install
      script:
        # Once this is on it's feet, I've pondered a broader os/version matrix test
        # (maybe in a separate branch, with a daily/weekly cron?) that can serve as
        # a reference for which combinations both do and don't currently work.
        - nix-env --version | grep "2.3.1"

    - name: add extra config to nix.conf
      os: linux
      before_install:
        # workaround: heredoc that ends on blank line
        - |
          cat << '' > extra.conf
          sandbox = relaxed
      env:
        - EXTRA_NIX_CONFIG: extra.conf
      script:
        # TODO: very basic; ideally this test should set a setting and confirm
        # a build that requires it runs clean, and that a separate build with the
        # option specified on the command-line fails.
        - grep "sandbox = relaxed" /etc/nix/nix.conf
