language: shell
install: source install.sh
script: nix-shell -p cowsay --command "cowsay wooo?"
# Bare "nix" command hidden behind a flag in unstable
# script: nix run nixpkgs.cowsay -c cowsay wooo?

_cachix_push: &cachix_push
  after_success:
    - comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all| grep -v '\.drv$' | sort) | cachix push $CACHIX_CACHE

jobs:
  include:
    # test the default install across many OS/versions

    - os: osx
      osx_image: xcode12
